// ------------ Hein ----------- //
import tearUpImage from "../../assets/skillsImgs/hein01-Tear-Up.png";
import mutilateImage from "../../assets/skillsImgs/hein02-Mutilate.png";
import identifyWeaknessImage from "../../assets/skillsImgs/hein03-Identify-Weakness.png";
import assaultSlashImage from "../../assets/skillsImgs/hein04-Assault-Slash.png";
import intimidationImage from "../../assets/skillsImgs/hein05-Intimidation.png";
import bloodRefluxImage from "../../assets/skillsImgs/hein06-Blood-Reflux.png";
import mercilessExplosionImage from "../../assets/skillsImgs/hein07-Merciless-Explosion.png";
import endOfTheLineImage from "../../assets/skillsImgs/hein08-End-Of-The-Line.png";
import rageSlashImage from "../../assets/skillsImgs/hein09-Rage-Slash.png";
import bloodStormImage from "../../assets/skillsImgs/hein10-Blood-Storm.png";
import endlessRageImage from "../../assets/skillsImgs/hein11-Endless-Rage.png";
import bloodiedRevengeImage from "../../assets/skillsImgs/hein13-Bloodied-Revenge.png";

// ------------ Joey ----------- //
import chemicalWeapon from "../../assets/skillsImgs/joey01-Chemical-Weapon.png";
import selfDestructingHealingDrone from "../../assets/skillsImgs/joey02-Self-Destructing-Healing-Drone.png";
import healingRay from "../../assets/skillsImgs/joey03-Healing-Ray.png";
import weakeningSmog from "../../assets/skillsImgs/joey04-Weakening-Smog.png";
import paralyzingDart from "../../assets/skillsImgs/joey05-Paralyzing-Dart.png";
import healthAugmentingPatch from "../../assets/skillsImgs/joey06-Health-Augmenting-Patch.png";
import healingVapor from "../../assets/skillsImgs/joey07-Healing-Vapor.png";
import chemicalSubstanceNo12 from "../../assets/skillsImgs/joey08-Chemical-Substance-No-12.png";
import healingPotion from "../../assets/skillsImgs/joey09-Healing-Potion.png";
import bioticField from "../../assets/skillsImgs/joey10-Biotic-Field.png";
import createPotion from "../../assets/skillsImgs/joey11-Create-Potion.png";
import protectingGas from "../../assets/skillsImgs/joey12-Protecting-Gas.png";

// ------------ Swizz ----------- //
import eveHelp from "../../assets/skillsImgs/sizz01-Eve-Help.png";
import incise from "../../assets/skillsImgs/sizz02-Incise.png";
import eveGuard from "../../assets/skillsImgs/sizz03-Eve-Guard.png";
import patchUp from "../../assets/skillsImgs/sizz04-Patch-Up.png";
import healingWave from "../../assets/skillsImgs/sizz06-Healing-Wave.png";
import timeToMove from "../../assets/skillsImgs/sizz07-Time-To-Move.png";
import hinderingAttack from "../../assets/skillsImgs/sizz08-Hindering-Attack.png";
import threadOfLife from "../../assets/skillsImgs/sizz09-Thread-Of-Life.png";
import colllectEve from "../../assets/skillsImgs/sizz10-Collect-Eve.png";
import strikeBack from "../../assets/skillsImgs/sizz15-Strike-Back.png";

// ------------ Trisha ----------- //
import shadowSlash from "../../assets/skillsImgs/trisha01-Shadow-Slash.png";
import shadowRaid from "../../assets/skillsImgs/trisha02-Shadow-Raid.png";
import mirrorImage from "../../assets/skillsImgs/trisha03-Mirror-Image.png";
import illusionStrike from "../../assets/skillsImgs/trisha04-Illusion-Strike.png";
import applyBandage from "../../assets/skillsImgs/trisha05-Apply-Bandage.png";
import shadowCurtain from "../../assets/skillsImgs/trisha06-Shadow-Curtain.png";
import shadowStep from "../../assets/skillsImgs/trisha07-Shadow-Step.png";
import heartPierce from "../../assets/skillsImgs/trisha08-Heart-Pierce.png";
import caughtOffGuard from "../../assets/skillsImgs/trisha09-Caught-Off-Guard.png";
import stealthWalk from "../../assets/skillsImgs/trisha13-Stealth-Walk.png";
import weaknessExposed from "../../assets/skillsImgs/trisha14-Weakness-Exposed.png";
import eviscerate from "../../assets/skillsImgs/trisha15-Eviscerate.png";

// ------------ Miss Chain ----------- //
import zoom from "../../assets/skillsImgs/missChain01-Zoom.png";
import bazzuum from "../../assets/skillsImgs/missChain02-Bazzuum.png";
import engineReload from "../../assets/skillsImgs/missChain03-Engine-Reload.png";
import playingWithFire from "../../assets/skillsImgs/missChain04-Playing-With-Fire.png";
import pursuit from "../../assets/skillsImgs/missChain05-Pursuit.png";
import leaveThisToMe from "../../assets/skillsImgs/missChain06-Leave-This-To-Me.png";
import engineBurner from "../../assets/skillsImgs/missChain07-Engine-Burner.png";
import fireGround from "../../assets/skillsImgs/missChain08-Fire-Ground.png";
import shredThemAll from "../../assets/skillsImgs/missChain09-Shred-Them-All.png";
import fromHeadToToe from "../../assets/skillsImgs/missChain11-From-Head-To-Toe.png";
import dismantleArmor from "../../assets/skillsImgs/missChain12-Dismantle-Armor.png";
import burningDraw from "../../assets/skillsImgs/missChain13-Burning-Draw.png";

// ------------ Azar ----------- //
import illusionSwordFirstScroll from "../../assets/skillsImgs/azar01-Illusion-Sword-First-Scroll.png";
import ascendingSlice from "../../assets/skillsImgs/azar02-Ascending-Slice.png";
import veiledSword from "../../assets/skillsImgs/azar03-Veiled-Sword.png";
import stormingBlade from "../../assets/skillsImgs/azar04-Storming-Blade.png";
import swordOfInfinity from "../../assets/skillsImgs/azar05-Sword-Of-Infinity.png";
import crescentSlash from "../../assets/skillsImgs/azar06-Crescent-Slash.png";
import shiningAura from "../../assets/skillsImgs/azar07-Shining-Aura.png";
import illusionFlash from "../../assets/skillsImgs/azar08-Illusion-Flash.png";
import illusionSwordsCalling from "../../assets/skillsImgs/azar09-Illusion-Swords-Calling.png";
import bladeStarfall from "../../assets/skillsImgs/azar10-Blade-Starfall.png";
import fantasy from "../../assets/skillsImgs/azar11-Fantasy.png";
import dancingSword from "../../assets/skillsImgs/azar12-Dancing-Sword.png";

// ------------ Lian ----------- //
import dropdownSlash from "../../assets/skillsImgs/lian01-Dropdown-Slash.png";
import riposte from "../../assets/skillsImgs/lian02-Riposte.png";
import bringItOn from "../../assets/skillsImgs/lian04-Bring-It-On.png";
import combatRoar from "../../assets/skillsImgs/lian05-Combat-Roar.png";
import relentlessSwipe from "../../assets/skillsImgs/lian06-Relentless-Swipe.png";
import stunningSmite from "../../assets/skillsImgs/lian07-Stunning-Smite.png";
import reprisal from "../../assets/skillsImgs/lian08-Reprisal.png";
import preparation from "../../assets/skillsImgs/lian09-Preparation.png";
import parryingTactics from "../../assets/skillsImgs/lian10-Parrying-Tactics.png";
import retribution from "../../assets/skillsImgs/lian11-Retribution.png";

// ------------ Phoenix ----------- //
import scratch from "../../assets/skillsImgs/phoenix01-Scratch.png";
import phoenixKick from "../../assets/skillsImgs/phoenix02-Phoenix-Kick.png";
import faceSlap from "../../assets/skillsImgs/phoenix03-Face-Slap.png";
import nibble from "../../assets/skillsImgs/phoenix05-Nibble.png";
import lecture from "../../assets/skillsImgs/phoenix07-Lecture.png";
import fieryWings from "../../assets/skillsImgs/phoenix08-Fiery-Wings.png";
import leer from "../../assets/skillsImgs/phoenix09-Leer.png";
import blazingRegeneration from "../../assets/skillsImgs/phoenix10-Blazing-Regeneration.png";
import legendaryBeak from "../../assets/skillsImgs/phoenix12-Legendary-Beak.png";
import treatTime from "../../assets/skillsImgs/phoenix14-Treat-Time.png";
import findBread from "../../assets/skillsImgs/phoenix15-Find-Bread.png";
import fetch from "../../assets/skillsImgs/phoenix16-Fetch.png";
import fly from "../../assets/skillsImgs/phoenix17-Fly.png";
import eternalFlame from "../../assets/skillsImgs/phoenix18-Eternal-Flame.png";
import undyingSanctuary from "../../assets/skillsImgs/phoenix19-Undying-Sanctuary.png";
import peck from "../../assets/skillsImgs/phoenix20-Peck.png";
import throwBread from "../../assets/skillsImgs/phoenix21-Throw-Bread.png";

// ------------ Pressel ----------- //
import healingCoil from "../../assets/skillsImgs/pressel01-Healing-Coil.png";
import holyLight from "../../assets/skillsImgs/pressel02-Holy-Light.png";
import firstClassToHeaven from "../../assets/skillsImgs/pressel03-First-Class-To-Heaven.png";
import killIt from "../../assets/skillsImgs/pressel04-Kill-It.png";
import blinkingHeal from "../../assets/skillsImgs/pressel05-Blinking-Heal.png";
import godsBlessing from "../../assets/skillsImgs/pressel06-Gods-Blessing.png";
import purifyingBarrier from "../../assets/skillsImgs/pressel07-Purifying-Barrier.png";
import doubleHeal from "../../assets/skillsImgs/pressel08-Double-Heal.png";
import shiningPillar from "../../assets/skillsImgs/pressel09-Shining-Pillar.png";
import adjustAim from "../../assets/skillsImgs/pressel10-Adjust-Aim.png";
import celestialWing from "../../assets/skillsImgs/pressel11-Celestial-Wing.png";
import guardianAngel from "../../assets/skillsImgs/pressel12-Guardian-Angel.png";
import divineRevelation from "../../assets/skillsImgs/pressel13-Divine-Revelation.png";

const skills = [
  // ------------ Hein ----------- //
  {
    id: 1,
    character: "Hein",
    name: "Tear Up",
    image: tearUpImage,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana",
    stats01: "Damage: 15 - Accuracy: 84% - Critical Hit: 0%.",
    Overload: "Overload",
    Countdown: "Countdown 1.",
    IgnoreTaunt: "Ignore Taunt.",
    CannotBeFixed: "Cannot Be Fixed.",
    castEffectLine01: "- Always lands against targets with a Weakening Debuff.",
    castEffectLine02: "- Attack an additional enemy with the lowest health.",
    castEffectLine03: "- If Facing one enemy, damage is increased by 7.",
    synergies: [
      "Overload",
      "Countdown",
      "Ignore Taunt",
      "Additional Damage",
      "Attack",
    ],
  },
  {
    id: 2,
    character: "Hein",
    name: "Mutilate",
    image: mutilateImage,
    targetting: "Random Enemy",
    cost: "Cost: 2 Mana",
    stats01: "Damage: 27 - Accuracy: 96% - Critical Hit: 0%.",
    Overload: "Overload",
    PriorityLowHP: "Priority Low HP",
    synergies: ["Overload", "Priority Low HP", "Attack"],
  },
  {
    id: 3,
    character: "Hein",
    name: "Identify Weakness",
    image: identifyWeaknessImage,
    targetting: "Single Enemy",
    cost: "Cost: 0 Mana",
    stats02:
      "Detect Weakness Debuff - Success Rate: 150% - Stacks Inflicted: (2/2).",
    Swiftness: "Swiftness",
    Once: "Once",
    DetectWeakness: "Detect Weakness",
    castEffectLine01: "- Inflicts target with the Detect Weakness Debuff.",
    synergies: [
      "Swiftness",
      "Once",
      "Detect-Weakness",
      "Armour Down",
      "Evade Down",
      "Debuff",
    ],
  },
  {
    id: 4,
    character: "Hein",
    name: "Assault Slash",
    image: assaultSlashImage,
    targetting: "All Enemies",
    cost: "Cost: 2 Mana",
    stats01: "Damage: 18 - Accuracy: 80% - Critical Hit: -10%.",
    Overload: "Overload",
    Countdown: "Countdown 01",
    castEffectLine01: "- Always lands against targets with a weakening Debuff.",
    castEffectLine02: "- If facing one enemy, damage is increased by 7.",
    synergies: [
      "Overload",
      "Countdown",
      "Debuff",
      "Additional Damage",
      "Attack",
    ],
  },
  {
    id: 5,
    character: "Hein",
    name: "Intimidation",
    image: intimidationImage,
    targetting: "All Enemies",
    cost: "Cost: 1 Mana",
    stats01: "Damage: 5 - Accuracy: 102% - Critical Hit: 0%.",
    stats02: " Fear - Debuff Success Rate: 115% - Stacks Inflicted (1/2).",
    Swiftness: "Swiftness",
    Fear: "Fear",
    synergies: [
      "Switness",
      "Once",
      "Fear",
      "Armour Down",
      "Evade Down",
      "Speed Down",
      "Recieving Crit Up",
      "Debuff",
      "Attack",
    ],
  },
  {
    id: 6,
    character: "Hein",
    name: "Blood Reflux",
    image: bloodRefluxImage,
    targetting: "Other Ally",
    cost: "Cost: 0 Mana",
    Swiftness: "Swiftness",
    Bloodthirst: "Bloodthirst",
    Tenacity: "Tenacity",
    PainDamage: "Pain Damage",
    RestoreHealingGauge: "Restore Healing Gauge",
    castEffectLine01:
      "- Restore the target's healing Gauge but receive Pain damage equal to half of the amount.",
    castEffectLine02: "- Inflicts the Target with Bloodthirst.",
    castEffectLine03: "- Inflicts Target with Tenacity (1/2).",
    synergies: [
      "Switness",
      "Bloodthirst",
      "Tenacity",
      "Pain Damage",
      "Restore Healing Gauge",
      "Buff",
    ],
  },
  {
    id: 7,
    character: "Hein",
    name: "Merciless Explosion",
    image: mercilessExplosionImage,
    targetting: "Single Enemy",
    cost: "Cost: 3 Mana",
    stats01: "Damage: 5 - Accuracy: 93% - Critical Hit: -5%.",
    Swiftness: "Swiftness",
    IgnoreTaunt: "Ignore Taunt",
    PainDamage: "Pain Damage",
    RestoreHealingGauge: "Restore Healing Gauge",
    castEffectLine01: "- Cannot be used at Death's Door.",
    castEffectLine02:
      "- Recieve Pain damage equal to 50% of Max Health (12), and deal additional damage equal to 2x missing health.",
    castEffectLine03: "- This skill cannot defeat an enemy.",
    castEffectLine04: "- Self: Tenacity (1/2).",
    synergies: [
      "Switness",
      "Pain Damage",
      "Healing Gauge Protection",
      "Additional Damage",
      "Attack",
    ],
  },
  {
    id: 8,
    character: "Hein",
    name: "End-Of-The-Line",
    image: endOfTheLineImage,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: "Damage: 21 - Accuracy: 89% - Critical Hit: 0%.",
    Overload: "Overload",
    IgnoreTaunt: "Ignore Taunt",
    castEffectLine01:
      "- Gain Igtnore Taunt and guaranteed Critical against targets whose health is 50% or below.",
    castEffectLine02:
      "- When the user is at Death's Door, gain Swiftness and deal 15 additional damage.",
    synergies: ["Overload", "Switness", "Ignore Taunt", "Crit Up", "Attack"],
  },
  {
    id: 9,
    character: "Hein",
    name: "Rage-Slash",
    image: rageSlashImage,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: "Damage: 22 - Accuracy: 89% - Critical Hit: 0%.",
    stats02:
      "Evade Reduced Debuff - Success Rate: 105% - Stacks Inflicted: (1/3).",
    Swiftness: "Swiftness",
    Countdown: "Countdown 2",
    IgnoreTaunt: "Ignore Taunt",
    EvadeReduced: "Evade Reduced",
    castEffectLine01:
      "- Reduce this skill's cost by 1 if the user has remaining Healing Gauge.",
    castEffectLine02: "- Reduce cost to 0 at Death's Door.",
    synergies: [
      "Switness",
      "Countdown",
      "Ignore Taunt",
      "Death's Door",
      "Mana Cost Down",
      "Evade Down",
      "Attack",
    ],
  },
  {
    id: 10,
    character: "Hein",
    name: "Blood Storm",
    image: bloodStormImage,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: "Damage: 18 - Accuracy: 89% - Critical Hit: 0%.",
    Overload: "Overload",
    Countdown: "Countdown 2",
    IgnoreTaunt: "Ignore Taunt",
    castEffectLine01:
      "- Deal damage equal to 70% of Max Health (17) + 50% of lost Health.",
    castEffectLine02:
      "- If you defeat an enemy with this skill, overheal 25% of Max Health.",
    synergies: ["Overload", "Ignore Taunt", "Additional Damage", "Attack"],
  },
  {
    id: 11,
    character: "Hein",
    name: "Endless Rage",
    image: endlessRageImage,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana",
    stats01: "Damage: 6 - Accuracy: 89% - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    CannotBeFixed: "Cannot Be Fixed",
    castEffectLine01:
      "- Deal additional damage equal to 25% of Max Health (6).",
    castEffectLine02:
      "- Whenever this skill is played from hand, receive Pain damage equal to additional damage.",
    castEffectLine02: "- This skill can be played repeatedly during this turn.",
    synergies: [
      "Swiftness",
      "Cannot Be Fixed",
      "Additional Damage",
      "Pain Damage",
      "Attack",
    ],
  },
  {
    id: 13,
    character: "Hein",
    name: "Bloodied Revenge",
    image: bloodiedRevengeImage,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: "Damage: 13 - Accuracy: 89% - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    CannotBeFixed: "Cannot Be Fixed",
    IgnoreTaunt: "Ignore Taunt",
    castEffectLine01:
      "- Converts damage recieved by party members into bonus damage for this skill. Cannot exceed Max health x2 (50).",
    castEffectLine02:
      "- Whenever this skill is played from hand, receive Pain damage equal to additional damage.",
    synergies: [
      "Swiftness",
      "Cannot Be Fixed",
      "Ignore Taunt",
      "Additional Damage",
      "Attack",
    ],
  },

  // ------------ Joey ----------- //

  {
    id: 14,
    character: "Joey",
    name: "Chemical Weapon",
    image: chemicalWeapon,
    targetting: "Ally",
    cost: "Cost: 1 Mana",
    Swiftness: "Swiftness",
    Intoxication: "Intoxication",
    ChemicalWeapon: "Chemical Weapon",
    castEffectLine01: "- Inflict target with the Chemical Weapon buff (3/3)",
    synergies: ["Swiftness", "Pain Damage", "Intoxication", "Debuff", "Buff"],
  },
  {
    id: 15,
    character: "Joey",
    name: "Self-Destructing Healing Drone",
    image: selfDestructingHealingDrone,
    targetting: "All Allies",
    cost: "Cost: 2 Mana",
    stats01: "Healing: 4 - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    CannotBeFixed: "Cannot Be Fixed",
    castEffectLine01:
      "- Deal 5 damage to a random enemy for every two buffs on all allies.",
    castEffectLine02: "- Based on Healing Power.",
    synergies: ["Swiftness", "Additional Damage", "Heal"],
  },
  {
    id: 16,
    character: "Joey",
    name: "Healing Ray",
    image: healingRay,
    targetting: "Single Ally",
    cost: "Cost: 1 Mana",
    stats01: "Healing: 15 - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    ChainHeal: "Chain Heal",
    castEffectLine01:
      "- Deal 5 damage to a random enemy for every two buffs on all allies.",
    castEffectLine02: "- Based on Healing Power.",
    synergies: ["Swiftness", "Additional Damage", "Chain Heal", "Heal"],
  },
  {
    id: 17,
    character: "Joey",
    name: "Weakening Smog",
    image: weakeningSmog,
    targetting: "All Enemies",
    cost: "Cost: 1 Mana",
    stats01: "Damage: 4 - Accuracy: 100% - Critical Hit: -5%",
    stats02:
      "Embrittlement Debuff - Success Rate: 105% - Stacks Inflicted: (1/3).",
    stats02: "Intoxication - Success Rate: 105% - Stacks Inflicted: (1/5).",
    Swiftness: "Swiftness",
    Embrittlement: "Embrittlement",
    Intoxication: "Intoxication",
    castEffectLine01: "- Inflicts all targets with the Embrittlement Debuff.",
    castEffectLine02: "- Inflicts all targets with the Intoxication Debuff.",
    synergies: ["Swiftness", "Once", "Embrittlement", "Intoxication", "Debuff"],
  },
  {
    id: 18,
    character: "Joey",
    name: "Paralyzing Dart",
    image: paralyzingDart,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: "Damage: 1 - Accuracy: 115% - Critical Hit: 0%.",
    stats02: "Stun Debuff - Success Rate: 135% - Stacks Inflicted: (1/1).",
    Swiftness: "Swiftness",
    CannotBeFixed: "Cannot Be Fixed",
    IgnoreTaunt: "Ignore Taunt",
    Stun: "Stun",
    castEffectLine01: "- Inflicts target with the Stun Debuff.",
    synergies: [
      "Swiftness",
      "Cannot Be Fixed",
      "Ignore Taunt",
      "Stun",
      "Debuff",
    ],
  },
  {
    id: 19,
    character: "Joey",
    name: "Health Augmenting Patch",
    image: healthAugmentingPatch,
    targetting: "Single Ally",
    cost: "Cost: 2 Mana",
    stats01: "Healing: 11 - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    MaxHealthIncreased: "Max Health Increased",
    castEffectLine01:
      "- Cast this skill on the target and the ally on their right side.",
    castEffectLine02:
      "- Inflicts all targets with the Max Health Increased buff (1/2).",
    synergies: ["Swiftness", "Max Health Increased", "Buff", "Heal"],
  },
  {
    id: 20,
    character: "Joey",
    name: "Healing Vapor",
    image: healingVapor,
    targetting: "All Allies",
    cost: "Cost: 2 Mana",
    Overload: "Overload",
    HealingVapor: "healing Vapor",
    castEffectLine01: "- Grants all allies the Healing Vapor buff.",
    synergies: ["Overload", "Heal", "Buff"],
  },
  {
    id: 21,
    character: "Joey",
    name: "Chemical Substance No.12",
    image: chemicalSubstanceNo12,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana",
    stats01: " Damage: 2 - Accuracy: 100% - Critical Hit: 0%.",
    stats02:
      " Intoxication Debuff - Success Rate: 115% - Stacks Inflicted: (2/5).",
    Overload: "Overload",
    Intoxication: "Intoxication",
    castEffectLine01:
      "- Additionally deal double the target's Pain damage per turn",
    castEffectLine01: "- Inflicts target with the Intoxication Debuff.",
    synergies: [
      "Overload",
      "Ignore Taunt",
      "Pain Damage",
      "Additional Damage",
      "Debuff",
    ],
  },
  {
    id: 22,
    character: "Joey",
    name: "Healing Potion",
    image: healingPotion,
    targetting: "Single Ally",
    cost: "Cost: 1 Mana",
    stats01: " Healing: 14 - Critical Hit: 0%.",

    Overload: "Overload",
    RegenerationJ: "Regeneration-J",
    castEffectLine01: "- Grants target ally regeneration-J)",
    synergies: ["Overload", "Regeneration", "Heal", "Buff"],
  },
  {
    id: 23,
    character: "Joey",
    name: "Biotic Field",
    image: bioticField,
    targetting: "All Allies",
    cost: "Cost: 1 Mana",
    stats01: " Healing: 14 - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    BioticField: "Biotic Field",
    castEffectLine01: "- Grants all allies Biotic Field.",
    synergies: ["Swiftness", "Once", "Heal", "Buff"],
  },
  {
    id: 24,
    character: "Joey",
    name: "Create Potion",
    image: createPotion,
    targetting: "Hand",
    cost: "Cost: 0 Mana",
    Swiftness: "Swiftness",
    castEffectLine01:
      "- Create a 2-cost Switness skill with effects of your choice.",
    synergies: ["Swiftness", "Create Skill"],
  },
  {
    id: 25,
    character: "Joey",
    name: "Protecting Gas",
    image: protectingGas,
    targetting: "All Allies",
    cost: "Cost: 1 Mana",
    stats01: " Healing: 5 - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    castEffectLine01: "- For each ally, remove one defuff.",
    synergies: ["Swiftness", "Heal", "Buff"],
  },

  {
    id: 26,
    character: "Sizz",
    name: "Eve, Help!",
    image: eveHelp,
    targetting: "Single Ally",
    cost: "Cost: 0 Mana",
    stats01: " Healing: 3 - Critical Hit: 0%",
    Overload: "Overload",
    EveDollAttack: "Eve Doll Attack",
    PincerAttack: "Pincer Attack",
    castEffectLine01: "- Transfer all Pincer Attack buffs to the target.",
    castEffectLine02:
      "- Create a 1 cost Swiftness 'Eve, Help!' skill in your hand.",
    castEffectLine03: "- The created skill can only be cast this turn.",
    synergies: [
      "Overload",
      "Eve Doll",
      "Pincer Attack",
      "Eve Doll Attack",
      "Heal",
      "Buff",
    ],
  },
  {
    id: 27,
    character: "Sizz",
    name: "Incise",
    image: incise,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana",
    stats01: " Damage: 12 - Accuracy: 100% - Critical Hit: -10%.",
    Overload: "Overload",
    EveDollAttack: "Eve Doll Attack",
    AmplifyEvesAttacks: "Amplify Eve's Attack",
    IgnoreTaunt: "Ignore Taunt",
    synergies: [
      "Overload",
      "Eve Doll",
      "Eve Doll Attack",
      "Amplify Eve's Attack",
      "ignore Taunt",
      "Attack",
    ],
  },
  {
    id: 28,
    character: "Sizz",
    name: "Eve, Guard!",
    image: eveGuard,
    targetting: "Single Ally",
    cost: "Cost: 1 Mana",
    stats01: " Healing: 15 - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    EvesProtection: "Eve's Protection",
    ChainHeal: "ChainHeal",
    castEffectLine01: "- Inflicts target with the buff: Eve's Protection.",
    synergies: ["Overload", "Eve Doll", "Chain Heal", "Heal", "Buff"],
  },
  {
    id: 29,
    character: "Sizz",
    name: "Patch Up",
    image: patchUp,
    targetting: "Single Ally",
    cost: "Cost: 1 Mana",
    stats01: " Healing: 12 - Critical Hit: 0%.",
    Overload: "Overload",
    Regeneration: "Regeneration",
    castEffectLine02: "- Inflicts target with the Regeneration Buff (1/3)",
    castEffectLine01:
      "- If Eve has 2 stacks, consume 1 stack to restore 1 mana",
    synergies: [
      "Overload",
      "Eve Doll",
      "Overheal",
      "Regeneration",
      "Mana Restore",
      "Heal",
      "Buff",
    ],
  },
  {
    id: 31,
    character: "Sizz",
    name: "Healing Wave",
    image: healingWave,
    targetting: "Single Ally",
    cost: "Cost: 1 Mana",
    stats01: " Healing: 7 - Critical Hit: 0%.",
    Overload: "Overload",
    castEffectLine01: "- Removes a random Debuff from a target.",
    castEffectLine02: "- All other allies except the target are healed.",
    synergies: ["Overload", "Eve Doll", "Remove Debuff", "Heal", "Buff"],
  },
  {
    id: 32,
    character: "Sizz",
    name: "Time To Move!",
    image: timeToMove,
    targetting: "Single Ally",
    cost: "Cost: 1 Mana",
    stats01: " Healing: 6 - Critical Hit: -10%.",
    Overload: "Overload",
    castEffectLine01:
      "- Add Strike Back! to your Eve's hand when this skill is cast.",
    synergies: ["Overload", "Eve Doll", "Heal", "Create Skill", "Buff"],
  },
  {
    id: 33,
    character: "Sizz",
    name: "Hindering Attack",
    image: hinderingAttack,
    targetting: "Single Ally",
    cost: "Cost: 1 Mana",
    stats01: " Healing: 4 - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    HinderingAttack: "Hindering Attack",
    castEffectLine01: "- Inflicts target with the Hindering Attack buff.",
    synergies: ["Swiftness", "Eve Doll", "Hindering Attack", "Heal", "Buff"],
  },
  {
    id: 34,
    character: "Sizz",
    name: "Therad Of Life",
    image: threadOfLife,
    targetting: "All Allies",
    cost: "Cost: 2 Mana",
    stats01: " Healing: 6 - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    castEffectLine01:
      "- When Eve has 2 stacks, consume 1 stack to restore 4 more health.",
    synergies: ["Swiftness", "Heal", "Buff"],
  },
  {
    id: 35,
    character: "Sizz",
    name: "Collect Eve",
    image: colllectEve,
    targetting: "Conditional Ally",
    cost: "Cost: 0 Mana",
    stats01: " Healing: 11 - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    Once: "Once",
    CannotBeFixed: "Cannot be Fixed",
    castEffectLine01: "- If Eve has 2 stacks, restore 2 mana.",
    castEffectLine02:
      "- The ally with Eve receives 11 barrier until next turn.",
    castEffectLine03: "- Remove Eve doll from any colleague.",
    synergies: [
      "Swiftness",
      "Once",
      "Cannot be Fixed",
      "Mana Restore",
      "Barrier",
    ],
  },
  {
    id: 40,
    character: "Sizz",
    name: "Strike Back!",
    image: strikeBack,
    targetting: "Single Ally",
    cost: "Cost: 0 Mana",
    stats01: " Healing: 1 - Critical Hit: -10%.",
    Swiftness: "Swiftness",
    Exclude: "Exclude",
    Discard: "Discarded After 1 turn",
    StrikeBack: "Strike Back!",
    castEffectLine01: "- Inflicts ally with the Strike Back! buff.",
    synergies: [
      "Swiftness",
      "Once",
      "Cannot be Fixed",
      "Discard",
      "Mana Restore",
      "Barrier",
    ],
  },

  // ------------ Trisha ----------- //

  {
    id: 41,
    character: "Trisha",
    name: "Shadow Slash",
    image: shadowSlash,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana",
    stats01: " Damage: 10 - Accuracy: 100% - Critical Hit: 10%.",
    stats02:
      "Recieving Crit Up Debuff - Success Rate: 100% - Stacks Applied: (1/3).",
    Swiftness: "Swiftness",
    IgnoreTaunt: "Ignore Taunt",
    RecievingCtitUp: "Recieving Crit Up",
    castEffectLine01: "- Can be recast if used on an enemy at full HP.",
    synergies: [
      "Swiftness",
      "Ignore Taunt",
      "Recieving Crit Up",
      "Recast",
      "Attack",
    ],
  },
  {
    id: 42,
    character: "Trisha",
    name: "Shadow Raid",
    image: shadowRaid,
    targetting: "Single Enemy",
    cost: "Cost: 3 Mana",
    stats01: " Damage: 21 - Accuracy: 105% - Critical Hit: 35%.",
    Overload: "Overload",
    castEffectLine01:
      "- Increase this skill's Critical Hit chance by 100% if none of the user's skills are in hand.",
    castEffectLine02:
      "- Exceeding Critical Hit chance is converted into Critical Damage.",
    synergies: ["Overload", "Crit Up", "Crit Dmg Up", "Attack"],
  },
  {
    id: 43,
    character: "Trisha",
    name: "Mirror Image",
    image: mirrorImage,
    targetting: "Hand",
    cost: "Cost: 0 Mana",
    Swiftness: "Swiftness",
    Once: "Once",
    CannotBeFixed: "CannotBeFixed",
    castEffectLine01: "- Select a skill in hand and duplicate it.",
    castEffectLine02:
      "- The duplicated skill becomes this character's skill, and this skill turns back to Mirror Image when cast.",
    castEffectLine03:
      "- Lucy Skills, Mirror Image, and Rare Skills cannot be selected.",
    synergies: ["Swiftness", "Once", "CannotBeFixed", "Create Skill"],
  },
  {
    id: 44,
    character: "Trisha",
    name: "Illusion Strike",
    image: illusionStrike,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 19 - Accuracy: 100% - Critical Hit: 20%.",
    stats02:
      "Recieving Crit Up Debuff - Success Rate: 115% - Stacks Applied: (1/1).",
    stats03: "Bleeding Debuff - Success Rate: 115% - Stacks Applied: (1/2).",
    Overload: "Overload",
    Critical: "Critical",
    Bleeding: "Bleeding",
    RecievingCritUp: "Recieving Crit Up",
    IgnoreTaunt: "Ignore Taunt",
    castEffectLine01: "- Choose one:",
    castEffectLine02: "- A) Apply the Recieving Crit Up Debuff to all enemies.",
    castEffectLine03: "- B) Apply the Bleeding Debuff to a single enemy.",
    synergies: [
      "Overload",
      "Ignore Taunt",
      "Critical",
      "Recieving Crit Up",
      "Pain Damage",
      "Attack",
      "Debuff",
    ],
  },
  {
    id: 45,
    character: "Trisha",
    name: "Apply Bandage",
    image: applyBandage,
    targetting: "Single Ally",
    cost: "Cost: 0 Mana",
    stats01: " Healing: 7 - Critical Hit: 10%",
    Overload: "Overload",
    castEffectLine01: "- Remove a random Pain Debuff.",
    castEffectLine02:
      "- If none of the user's skills are in hand, draw one at random.",
    synergies: [
      "Overload",
      "Remove Debuff",
      "Draw",
      "Recieving Crit Up",
      "Pain damage",
      "Buff",
    ],
  },
  {
    id: 46,
    character: "Trisha",
    name: "Shadow Curtain",
    image: shadowCurtain,
    targetting: "Single Ally",
    cost: "Cost: 0 Mana",
    stats01: "Stun Debuff - Success Rate: 115% - Stacks Applied: (1/1).",
    Swiftness: "Swiftness",
    CannotBeFixed: "CannotBeFixed",
    Stun: "Stun",
    ShadowVeil: "ShadowVeil",
    Exclude: "Exclude After 3 Uses",
    castEffectLine01: "- Apply Shadow Veil to the target.",
    castEffectLine02:
      "- If used in Double Team, apply Stun to a random enemy and gain 25% Critical Rate for 2 turns.",
    synergies: [
      "Swiftness",
      "Exclude",
      "CannotBeFixed",
      "Stun",
      "Crit Up",
      "Debuff",
      "Buff",
    ],
  },
  {
    id: 47,
    character: "Trisha",
    name: "Shadow Step",
    image: shadowStep,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana",
    stats01: " Damage: 4 - Accuracy: 100% - Critical Hit: 10%.",
    stats03: "Taunt Debuff - Success Rate: 150% - Stacks Applied: (1/1).",
    Swiftness: "Swiftness",
    Once: "Once",
    IgnoreTaunt: "Ignore Taunt",
    Taunt: "Taunt",
    Exclude: "Exclude After 3 Uses",
    castEffectLine01: "- Apply Taunt to the target.",
    castEffectLine02: "- Choose one:",
    castEffectLine03:
      "- A) Duplicate a non-Rare attack skill that was played by a party member this turn.",
    castEffectLine04: "- The Duplicated Skill Becomes this character's skill.",
    castEffectLine05:
      "- B) Grant a Critical Chance Up: 8% buff to all allies for 4 turns.",
    synergies: [
      "Swiftness",
      "Once",
      "Ignore Taunt",
      "Create Skill",
      "Crit Up",
      "Attack",
      "Debuff",
      "Buff",
    ],
  },
  {
    id: 48,
    character: "Trisha",
    name: "Heart Pierce",
    image: heartPierce,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana",
    stats01: " Damage: 14 - Accuracy: 100% - Critical Hit: 20%.",
    stats02:
      "Heart Pierec Debuff - Success Rate: 115% - Stacks Applied: (1/1).",
    Overload: "Overload",
    CannotBeFixed: "CannotBeFixed",
    IgnoreTaunt: "Ignore Taunt",
    Critical: "Critical",
    HeartPierce: "HeartPierce",
    castEffectLine01: "- Apply the Heart Pierce Debuff to target.",
    synergies: [
      "Overload",
      "CannotBeFixed",
      "Ignore Taunt",
      "Crit Up",
      "Attack",
      "Debuff",
    ],
  },
  {
    id: 52,
    character: "Trisha",
    name: "Caught Off Guard",
    image: caughtOffGuard,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 18 - Accuracy: 100% - Critical Hit: -20%.",
    Overload: "Overload",
    CannotBeFixed: "CannotBeFixed",
    IgnoreTaunt: "Ignore Taunt",
    Critical: "Critical",
    Stun: "Stun",
    castEffectLine01:
      "- Deal 19 additional damage if an ally is Stunned or the target is CC Debuffed.",
    synergies: [
      "Overload",
      "CannotBeFixed",
      "Ignore Taunt",
      "Stun",
      "Additional Damage",
      "Attack",
    ],
  },
  {
    id: 53,
    character: "Trisha",
    name: "Weakness Exposed",
    image: weaknessExposed,
    targetting: "All Enemeies",
    cost: "Cost: 0 Mana",
    stats02:
      " Recieving Crit Up Debuff - Success Chance: 115% - Stacks Applied: (1/1).",
    Overload: "Overload",
    RecievingCritUp: "RecievingCritUp",
    castEffectLine01:
      "- Inflict all targets with the Recieving Crit Up Debuff.",
    synergies: ["Overload", "Recieving Crit Up", "Debuff"],
  },
  {
    id: 54,
    character: "Trisha",
    name: "Eviscerate",
    image: eviscerate,
    targetting: "Single Enemy",
    cost: "Cost: 0 Mana",
    stats02: "Bleeding Debuff - Success Chance: 115% - Stacks Applied: (1/2).",
    Overload: "Overload",
    Bleeding: "Bleeding",
    castEffectLine01: "- Inflict target with the Bleeding Debuff.",
    synergies: ["Overload", "Pain Damage", "Debuff"],
  },

  // ------------ Miss Chain ----------- //

  {
    id: 55,
    character: "Miss Chain",
    name: "Zoom!",
    image: zoom,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana",
    stats01: " Damage: 14 - Accuracy: 98% - Critical Hit: 5%",
    stats02:
      "- Armour Reduced! Debuff - Success Chance: 108% - Stacks Applied: (2/3)",
    Overload: "Overload",
    ArmorReduced: "Armor Reduced!",
    castEffectLine01: "- Inflict target with the Armour Reduced! Debuff.",
    synergies: ["Overload", "Armour Down", "Attack", "Debuff"],
  },
  {
    id: 56,
    character: "Miss Chain",
    name: "Bazzuum!",
    image: bazzuum,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 19 - Accuracy: 102% - Critical Hit: 15%.",
    stats02:
      "Armour Reduced! Debuff - Success Chance: 108% - Stacks Applied: (2/3).",
    Overload: "Overload",
    Countdown: "Countdown",
    ChainHeal: "ChainHeal",
    castEffectLine01: "- Gain Swiftness when HP is bellow 33%.",
    castEffectLine02:
      "- Burnnn! Active - Consume Burnnn! and chain heal the user for 50% max HP.",
    synergies: [
      "Overload",
      "Countdown",
      "Burnnn!",
      "Chain Heal",
      "Attack",
      "Debuff",
    ],
  },
  {
    id: 57,
    character: "Miss Chain",
    name: "Engine Reload!",
    image: engineReload,
    targetting: "Self",
    cost: "Cost: 0 Mana",
    stats02:
      "- Armour Reduced! Debuff - Success Chance: 108% - Stacks Applied: (2/3).",
    Swiftness: "Swiftness",
    Innate: "Innate",
    Screach: "Screach",
    Aggro: "Aggro",
    DeathsDoorImmunity: "Death's Door Immunity.",
    castEffectLine01:
      "- Inflict target with the Death's Door Imunity Buff (1/2).",
    castEffectLine02: "- Inflict target with the Screech Buff.",
    synergies: [
      "Swiftness",
      "Innate",
      "Death's Door Immunity",
      "maximum HP",
      "Aggro",
      "Attack",
      "Debuff",
    ],
  },
  {
    id: 58,
    character: "Miss Chain",
    name: "Playing With Fire",
    image: playingWithFire,
    targetting: "All Enemies",
    cost: "Cost: 1 Mana",
    stats01: " Damage: 5 - Accuracy: 91% - Critical Hit: 0%.",
    stats02:
      "- Grievous Burn Debuff - Success Chance: 113% - Stacks Applied: (1/4).",
    Overload: "Overload",
    GrievousBurn: "Grievous Burn",
    castEffectLine01: "- Inflict targets with Grievous Burn Debuff.",
    castEffectLine02:
      "- Burnnn! active - All enemy Pain and Weakening Debuffs remain an extra turn.",
    synergies: [
      "Overload",
      "Burnnn!",
      "Pain Damage",
      "Grievous Burn",
      "Attack",
      "Debuff",
    ],
  },
  {
    id: 59,
    character: "Miss Chain",
    name: "Leave This to Me!",
    image: leaveThisToMe,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana",
    stats01: " Damage: 8 - Accuracy: 107% - Critical Hit: 0%.",
    stats02: " taunted Debuff - Success Rate: 128% - Stacks Inflicted: (2/3).",
    Overload: "Overload",
    Innate: "Innate",
    IgnoreTaunt: "Ignore Taunt",
    Taunt: "Taunt",
    DeathsDoorImmunity: "Death's Door Immunity.",
    castEffectLine01: "- Inflict target with the Taunted! Debuff",
    castEffectLine02:
      "- Burnnn! active - gain a buff that lets the user counterattack enemy actions for 3 turns.",
    synergies: [
      "Overload",
      "Innate",
      "Ignore Taunt",
      "Taunted!",
      "Death's Door Immunity",
      "Parry",
      "Attack",
      "Debuff",
    ],
  },
  {
    id: 60,
    character: "Miss Chain",
    name: "Engine Burner",
    image: engineBurner,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 7 - Accuracy: 102% - Critical Hit: 0%",
    stats02:
      "Grievous Burn Debuff - Success Rate: 113% - Stacks Inflicted: (1/4) or (3/4).",
    Swiftness: "Swiftness",
    IgnoreTaunt: "Ignore Taunt",
    GrievousBurn: "Grievous Burn",
    Taunt: "Taunt",
    DeathsDoorImmunity: "Death's Door Immunity.",
    castEffectLine01: "- Inflict target with the Grievous Burn Debuff.",
    castEffectLine01:
      "- Burnnn! active: Inflict target with 3 stacks of the Grievous Burn Debuff instead.",
    synergies: [
      "Swiftness",
      "Ignore Taunt",
      "GrievousBurn",
      "Pain Damage",
      "Attack",
      "Debuff",
    ],
  },
  {
    id: 61,
    character: "Miss Chain",
    name: "Fire Ground",
    image: fireGround,
    targetting: "All Allies",
    cost: "Cost: 1 Mana",
    Overload: "Overload",
    Once: "Once",
    FlameBarrier: "Flame Barrier",
    GrievousBurn: "Grievous Burn",
    DeathsDoorImmunity: "Death's Door Immunity.",
    castEffectLine01: "- Inflicts all allies with the Flame Barrier buff.",
    castEffectLine02:
      "- Burnnn! active: user recieves a buff that reduces damage from the next attack recieved to 1.",
    synergies: [
      "Overload",
      "Once",
      "Burnnn!",
      "GrievousBurn",
      "Pain Damage",
      "Buff",
    ],
  },
  {
    id: 62,
    character: "Miss Chain",
    name: "Shred Them All",
    image: shredThemAll,
    targetting: "All Enemies",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 9 - Accuracy: 98% - Critical Hit: 0%.",
    stats02:
      " Amror Reduced! Debuff - Success Rate: 108%, Stacks Inflicted: (1/3).",
    Overload: "Overload",
    ArmorReducedMC: "Armour Reduced!",
    castEffectLine01: "- Inflicts all enemies with Armour Reduced!.",
    castEffectLine02:
      "- Burnnn! active: Increase all enemy Pain and Weakening Debuff stacks by 1.",
    synergies: [
      "Overload",
      "Burnnn!",
      "Armour Reduced!",
      "Armour Down",
      "Attack",
      "Debuff",
    ],
  },
  {
    id: 63,
    character: "Miss Chain",
    name: "From Head To Toe",
    image: fromHeadToToe,
    targetting: "Single Enemy",
    cost: "Cost: 3 Mana",
    stats01: " Damage: 24 - Accuracy: 98% - Critical Hit: 0%.",
    Overload: "Overload",
    DeathsDoorImmunity: "Death's Door Immunity.",
    castEffectLine01: "- Inflicts self with Death's Door Immunity (1/2).",
    castEffectLine02:
      "- Burnnn! active: Heal all other allies for 50% of Miss Chain's max HP.",
    castEffectLine03:
      "Burnnn! innactive: Deal 33% of Miss Chain's Max HP as additional damage.",
    synergies: [
      "Overload",
      "Burnnn!",
      "Heal",
      "Additional Damage",
      "Attack",
      "Heal",
      "Debuff",
    ],
  },
  {
    id: 64,
    character: "Miss Chain",
    name: "Dismantle Armor",
    image: dismantleArmor,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 21 - Accuracy: 98% - Critical Hit: 0%.",
    stats02:
      " Dismantle Armor Debuff - Success Rate: 148%, Stacks Inflicted: (5/10).",
    Overload: "Overload",
    DismantleArmor: "Dismantle Armour",
    castEffectLine01: "- This skill can only be played if Burnnn! is active.",
    castEffectLine02: "- Inflicts target with the dismantle armor Debuff.",
    synergies: [
      "Overload",
      "Burnnn!",
      "Dismantle Armor",
      "Armor Down",
      "Attack",
      "Debuff",
    ],
  },

  // ------------ Azar ----------- //

  {
    id: 65,
    character: "Azar",
    name: "Illusion Srord: First Scroll",
    image: illusionSwordFirstScroll,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana",
    stats01: " Damage: 13 - Accuracy: 96% - Critical Hit: 0%.",
    Overload: "Overload",
    IgnoreTaunt: "Ignore Taunt",
    IllusionSword: "Illusion Sword",
    castEffectLine01:
      "- Skills above this skill in hand gain an Illusion Sword buff.",
    synergies: ["Overload", "Illusion Sword", "Ignore Taunt", "Attack"],
  },
  {
    id: 66,
    character: "Azar",
    name: "Ascending Slice",
    image: ascendingSlice,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 18 - Accuracy: 96% - Critical Hit: 0%.",
    Overload: "Overload",
    IgnoreTaunt: "Ignore Taunt",
    IllusionSword: "Illusion Sword",
    castEffectLine01: "- Duplicate all Illusion Swords in hand.",
    castEffectLine02: "- Duplicated until hand is full.",
    synergies: [
      "Overload",
      "Illusion Sword",
      "Ignore Taunt",
      "Create Skill",
      "Attack",
    ],
  },
  {
    id: 67,
    character: "Azar",
    name: "Veiled Sword",
    image: veiledSword,
    targetting: "Other Ally",
    cost: "Cost: 1 Mana",
    stats01: " Damage: 18 - Accuracy: 96% - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    IgnoreTaunt: "Ignore Taunt",
    IllusionSword: "Illusion Sword",
    VeiliedSword: "Veiled Sword",
    castEffectLine01:
      "- Fill hand with selected Ally's version of Illusion Sword.",
    castEffectLine02: "- Inflicts target with the Veiled Sword buff (2/5).",
    castEffectLine02: "- Those Illusion Swords deal 6 damage each.",
    synergies: [
      "Swiftness",
      "Illusion Sword",
      "Veiled Sword",
      "Create Skill",
      "Buff",
    ],
  },
  {
    id: 68,
    character: "Azar",
    name: "Storming Blade",
    image: stormingBlade,
    targetting: "Single Enemy",
    cost: "Cost: 6 Mana",
    stats01: " Damage: 23 - Accuracy: 96% - Critical Hit: 10%.",
    Overload: "Overload",
    Countdown: "Countdown 1",
    IgnoreTaunt: "Ignore Taunt",
    IllusionSword: "Illusion Sword",
    castEffectLine01:
      "- Cost reduced by 1 mana each time a 0-cost skill is played while this card is in your hand.",
    synergies: [
      "Overload",
      "Countdown",
      "Ignore Taunt",
      "Illusion Sword",
      "Mana Cost Down",
      "Attack",
    ],
  },
  {
    id: 69,
    character: "Azar",
    name: "Sword Of Infinity",
    image: swordOfInfinity,
    targetting: "Hand",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 23 - Accuracy: 96% - Critical Hit: 10%.",
    Swiftness: "Swiftness",
    Once: "Once",
    CannotBeFixed: "Cannot Be Fixed",
    IllusionSword: "Illusion Sword",
    castEffectLine01: "- Appply Illusion Sword buff to all skills in hand.",
    synergies: [
      "Switness",
      "Once",
      "Cannot Be Fixed",
      "Illusion Sword",
      "Buff",
    ],
  },
  {
    id: 69,
    character: "Azar",
    name: "Crescent Slash",
    image: crescentSlash,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 18 - Accuracy: 96% - Critical Hit: 10%.",
    Overload: "Overload",
    IgnoreTaunt: "Ignore Taunt",
    IllusionSword: "Illusion Sword",
    castEffectLine01: "- Can be cast twice if it has the Illusion Sword buff.",
    synergies: ["Overload", "Ignore Taunt", "Illusion Sword", "Attack"],
  },
  {
    id: 70,
    character: "Azar",
    name: "Shining Aura",
    image: shiningAura,
    targetting: "Self",
    cost: "Cost: 1 Mana",
    Swiftness: "Swiftness",
    ShiningAura: "Shining Aura",
    IllusionSword: "Illusion Sword",
    castEffectLine01: "- Apply Illusion Sword buff to 1 skill in hand.",
    castEffectLine02:
      "- Illusion Sword buff is applied to the top skill in hand without it.",
    castEffectLine03:
      "- Inflict self with the Shining Aura buff until the end of the turn.",
    synergies: ["Swiftness", "Illusion Sword", "Shining Aura", "Buff"],
  },
  {
    id: 71,
    character: "Azar",
    name: "Illusion Flash",
    image: illusionFlash,
    targetting: "Single Enemy",
    cost: "Cost: 3 Mana",
    Overload: "Overload",
    IllusionSword: "Illusion Sword",
    castEffectLine01:
      "- Repetedly deal 7 damage for each Illusion Sword and Illusion Sword buff in hand.",
    synergies: ["Overload", "Illusion Sword", "Additional Damage", "Attack"],
  },
  {
    id: 72,
    character: "Azar",
    name: "Illusion Sword's Calling",
    image: illusionSwordsCalling,
    targetting: "Hand",
    cost: "Cost: 1 Mana",
    Swiftness: "Swiftness",
    Discard: "Discarded After 2 Turns",
    IllusionSword: "Illusion Sword",
    castEffectLine01: "- Choose one:",
    castEffectLine02: "- A) Create 2 Illusion Swords in Hand.",
    castEffectLine03: "- B) Apply Illusion Sword to 2 skills in hand.",
    synergies: [
      "Swiftness",
      "Discard",
      "Illusion Sword",
      "Create Skill",
      "Buff",
    ],
  },
  {
    id: 73,
    character: "Azar",
    name: "Blade Starfall",
    image: bladeStarfall,
    targetting: "All Enemies",
    cost: "Cost: 3 Mana",
    stats01: " Damage: 11 - Accuracy: 96% - Critical Hit: -10%.",
    Swiftness: "Swiftness",
    Countdown: "Countdown 2",
    CannotBeFixed: "Cannot Be Fixed",
    IllusionSword: "Illusion Sword",
    castEffectLine01:
      "- Cast Illusion Sord skills on enemies at random equal to the sum of the cost of skills with the Illusion Sword Buff.",
    castEffectLine02:
      "- Illusion Swords Critical Hit if there is only 1 enemy.",
    synergies: [
      "Swiftness",
      "Countdown",
      "Cannot Be Fixed",
      "Illusion Sword",
      "Create Skill",
      "Attack",
    ],
  },
  {
    id: 74,
    character: "Azar",
    name: "Fantasy",
    image: fantasy,
    targetting: "Hand",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 11 - Accuracy: 96% - Critical Hit: -10%.",
    Swiftness: "Swiftness",
    Once: "Once",
    CannotBeFixed: "Cannot Be Fixed",
    IllusionSword: "Illusion Sword",
    castEffectLine01:
      "- Discard all 0 0-cost skills from hand and draw (discarded count + 1) skills.",
    castEffectLine02: "- These skills cost 0 and gain Swiftness.",
    castEffectLine03: "- Fantasy cannot reduce another Fantasy skill's cost.",
    synergies: [
      "Swiftness",
      "Once",
      "Cannot Be Fixed",
      "Illusion Sword",
      "Mana Cost Down",
      "Create Skill",
    ],
  },
  {
    id: 75,
    character: "Azar",
    name: "Dancing Sword",
    image: dancingSword,
    targetting: "Self",
    cost: "Cost: 1 Mana",
    Overload: "Overload",
    CannotBeFixed: "Cannot Be Fixed",
    IllusionSword: "Illusion Sword",
    castEffectLine01:
      "- Until the end of the turn, whenever you play a Single Target attack card, cast Illusion Sword on the target.",
    castEffectLine02: "- These skills cost 0 and gain Swiftness.",
    synergies: [
      "Overload",
      "Cannot Be Fixed",
      "Illusion Sword",
      "Create Skill",
    ],
  },

  // ------------ Lian ----------- //

  {
    id: 76,
    character: "Lian",
    name: "Dropdown Slash",
    image: dropdownSlash,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 21 - Accuracy: 100% - Critical Hit: 0%.",
    stats02: " Reduce Armor Debuff - Success Rate: 105%, Stacks Applied: N/A.",
    Overload: "Overload",
    Countdown: "Countdown 3",
    ArmorReduced: "Armor Reduced",
    castEffectLine01: "- Ignores enemy's Armour.",
    castEffectLine02:
      "- Inflictes target with the Armour Reduced Debuff for 3 turns",
    synergies: [
      "Overload",
      "Countdown",
      "Armor Reduced",
      "Armour Down",
      "Attack",
    ],
  },
  {
    id: 77,
    character: "Lian",
    name: "Riposte",
    image: riposte,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana",
    stats01: " Damage: 14 - Accuracy: 100% - Critical Hit: 0%.",
    stats02: " Reduce Armor Debuff - Success Rate: 105%, Stacks Applied: N/A.",
    Overload: "Overload",
    IgnoreTaunt: "Ignore Taunt",
    Countdown: "Countdown 2",
    ArmorReduced: "Armor Reduced",
    castEffectLine01: "- Critical Hit when cast by Lian's Parry.",
    castEffectLine02:
      "- Inflictes target with the Armour Reduced Debuff for 1 turn",
    synergies: [
      "Overload",
      "Countdown",
      "Ignore Taunt",
      "Parry",
      "Armor Reduced",
      "Armour Down",
      "Attack",
    ],
  },
  {
    id: 78,
    character: "Lian",
    name: "Riposte",
    image: riposte,
    targetting: "All Enemies",
    cost: "Cost: 2 Mana",
    stats02: " Taunted Debuff - Success Rate: 105%, Stacks Applied: (1/3).",
    Swiftness: "Swiftness",
    CannotBeFixed: "Cannot Be Fixed",
    Exclude: "Exclude",
    ArmorReduced: "Armor Reduced",
    castEffectLine01: "- Inflict all targets with the Taunted! Debuff",
    castEffectLine02:
      "- Create 2 random attack skills of party members in hand.",
    castEffectLine03:
      "- These skills gain Exclude and deal half of the skill's original damage.",
    castEffectLine04:
      "- When an enemy attacks any ally, these skills are automatically cast on the attacker.",
    synergies: [
      "Swiftness",
      "Cannot Be Fixed",
      "Exclude",
      "Taunted!",
      "Create Skill",
    ],
  },
  {
    id: 79,
    character: "Lian",
    name: "Combat Roar",
    image: combatRoar,
    targetting: "Hand",
    cost: "Cost: 1 Mana",
    Overload: "Overload",
    castEffectLine01:
      "- The first 5 skills in hand gain 100% Crit Rate until cast.",
    castEffectLine02: "- All allies gain 25% Crit Dmg until for this battle.",
    synergies: ["Overload", "Once", "Crit Up", "Crit Dmg Up", "Buff"],
  },
  {
    id: 80,
    character: "Lian",
    name: "Relentless Swipe",
    image: riposte,
    targetting: "All Enemies",
    cost: "Cost: 3 Mana",
    stats01: " Damage: 18 - Accuracy: 100% - Critical Hit: 0%.",
    stats02:
      " Relentless Swipe Debuff - Success Rate: 105%, Stacks Applied: (1/3).",
    Overload: "Overload",
    Countdown: "Countdown 2",
    RelentlessSwipe: "Relentless Swipe",
    castEffectLine01: "- Inflict all targets with the Relentless Swipe Debuff",
    castEffectLine02:
      "- Cost reduced by 1 for this turn if an ally takes Pain damage while this card is in hand",
    synergies: [
      "Overload",
      "Countdown",
      "Evade Down",
      "Recieving Crit Up",
      "Cost Reduced",
      "Pain Damage",
      "Attack",
    ],
  },
  {
    id: 81,
    character: "Lian",
    name: "Stunning Smite",
    image: stunningSmite,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 18 - Accuracy: 100% - Critical Hit: 0%.",
    stats02: " Stun Debuff - Success Rate: 110%, Stacks Applied: (1/1).",
    Swiftness: "Swiftness",
    CannotBeFixed: "Cannot Be Fixed",
    Countdown: "Countdown 4",
    Stun: "Stun",
    castEffectLine01:
      "- If you defeat an enemy with this skill, stun a random enemy",
    castEffectLine02:
      "- Cost reduced by 1 for this turn if an ally takes Pain damage while this card is in hand",
    synergies: [
      "Swiftness",
      "Countdown",
      "Cannot Be Fixed",
      "Stun",
      "Attack",
      "Debuff",
    ],
  },
  {
    id: 82,
    character: "Lian",
    name: "Reprisal",
    image: reprisal,
    targetting: "Single ally",
    cost: "Cost: 1 Mana",
    Swiftness: "Swiftness",
    CannotBeFixed: "Cannot Be Fixed",
    castEffectLine01:
      "- Remove a random Debuff from the target ally and generate a random attack skill.",
    castEffectLine02:
      "- The generated Skill inflicts the Debuff that was removed on it's target/s.",
    synergies: [
      "Swiftness",
      "Cannot Be Fixed",
      "Remove Debuff",
      "Generate Skill",
    ],
  },
  {
    id: 83,
    character: "Lian",
    name: "Preperation",
    image: preparation,
    targetting: "Self",
    cost: "Cost: 1 Mana",
    Overlaod: "Overlaod",
    Preparation: "Preparation",
    castEffectLine01: "- Inflict target with the Preperation buff (3/4).",
    synergies: ["Overlaod", "Parry", "Buff"],
  },
  {
    id: 84,
    character: "Lian",
    name: "Parrying Tactics",
    image: parryingTactics,
    targetting: "Single Ally",
    cost: "Cost: 1 Mana",
    Swiftness: "Swiftness",
    CannotBeFixed: "Cannot Be Fixed",
    castEffectLine01:
      "- View 3 random skills of target ally, then select 1 to add to hand.",
    castEffectLine02: "- The skill gains Countdown 2 and Exclude.",
    castEffectLine03: "- The selected ally is allowed to Parry once.",
    synergies: [
      "Swiftness",
      "Countdown",
      "Cannot Be Fixed",
      "Exclude",
      "Parry",
      "Create Skill",
      "Buff",
    ],
  },
  {
    id: 85,
    character: "Lian",
    name: "Retribution",
    image: retribution,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 20 - Accuracy: 100% - Critical Hit: 0%.",
    Overload: "Overload",
    Countdown: "Countdown 1",
    CannotBeFixed: "Cannot Be Fixed",
    castEffectLine01:
      "- Deal 10 damage to all other enemies except the target.",
    castEffectLine01:
      "- If cast by Lian's Parry, this skill can be reused this turn at 0 cost, Swiftness.",
    synergies: [
      "Overload",
      "Countdown",
      "Cannot Be Fixed",
      "Swiftness",
      "Parry",
      "Create Skill",
      "Attack",
    ],
  },

  // ------------ Phoenix ----------- //

  {
    id: 86,
    character: "Phoenix",
    name: "Scratch",
    image: scratch,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana",
    stats01: " Damage: 13 - Accuracy: 95% - Critical Hit: 0%.",
    Overload: "Overload",
    Hungry: "Hungry",
    Overheal: "Overheal",
    castEffectLine01: "- This skill always casts even if Hungry.",
    castEffectLine01:
      "- If Hungry, 50% chance to attack the highest health ally for 10 pain damage.",
    castEffectLine01:
      "- Overheal 15% Max Health whenever the user deals samage with this skill.",
    synergies: ["Overload", "Hungry", "Pain Damage", "Overheal", "Attack"],
  },
  {
    id: 87,
    character: "Phoenix",
    name: "Phoenix Kick!",
    image: phoenixKick,
    targetting: "Single Enemy",
    cost: "Cost: 4 Mana",
    stats01: " Damage: 19 - Accuracy: 95% - Critical Hit: 0%.",
    Overload: "Overload",
    IgnoreTaunt: "Ignore Taunt",
    castEffectLine01:
      "- Deal 0 additional damage if this skill is cast by a special effect from another skill such as lecture",
    castEffectLine01:
      "- Whenever this skill is cast, permenently increase additional damage by 4 for this entire run.",
    synergies: ["Overload", "Ignore Taunt", "Additional Damage", "Attack"],
  },
  {
    id: 88,
    character: "Phoenix",
    name: "Face Slap",
    image: faceSlap,
    targetting: "Single Enemy",
    cost: "Cost: 0 Mana",
    stats01: " Damage: 22 - Accuracy: 95% - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    Once: "Once",
    IgnoreTaunt: "Ignore Taunt",
    castEffectLine01:
      "- Can be played this turn if you cast a skill that costs 3 or more.",
    castEffectLine02: "- Cannot be played otherwise.",
    castEffectLine01:
      "- This limit is ignored when cast by a special effect such as lecture.",
    synergies: ["Swiftness", "Once", "Ignore Taunt", "Attack"],
  },
  {
    id: 90,
    character: "Phoenix",
    name: "Nibble",
    image: nibble,
    targetting: "Other Ally",
    cost: "Cost: 0 Mana",
    Overload: "Overload",
    Overheal: "Overheal",
    Absurdity: "Absurdity",
    castEffectLine01:
      "- Deal 13 Pain damage to an ally based on this skill user's Max HP.",
    castEffectLine02: "- Overheal this skills user for 13.",
    castEffectLine03: "- Inflict target with the Absurdity buff.",
    synergies: [
      "Overload",
      "Absurdity",
      "Attack Up",
      "Healing Power Up",
      "Pain Damage",
      "Overheal",
      "Heal",
    ],
  },
  {
    id: 92,
    character: "Phoenix",
    name: "Lecture",
    image: lecture,
    targetting: "Deck",
    cost: "Cost: 1 Mana",
    Swiftness: "Swiftness",
    castEffectLine01: "- Duplicate and draw the topmost skill in the Deck.",
    castEffectLine02: "- Cast it on a random target.",
    castEffectLine03:
      "- Add Fly as an option in Phoenix's Might. Fly can be used twice per battle.",
    synergies: ["Swiftness", "Create Skill"],
  },
  {
    id: 93,
    character: "Phoenix",
    name: "Fiery Wings",
    image: fieryWings,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 19 - Accuracy: 95% - Critical Hit: 50%.",
    Swiftness: "Swiftness",
    castEffectLine01:
      "- If theis skill did not defeat the target, heal all enemies except the target for 80.",
    castEffectLine02: "- Add Fetch as an option to Phoenix's Might.",
    synergies: ["Swiftness", "Create Skill", "Attack"],
  },
  {
    id: 94,
    character: "Phoenix",
    name: "Leer",
    image: leer,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana",
    stats02: " Taunted! Debuff - Success Rate: 130% - Stacks Inflicted: (2/3).",
    stats03:
      " Whatcha' Looking at? Debuff - Sucess Rate: Guarenteed - Stacks Inflicted: (1/3).",
    Swiftness: "Swiftness",
    Taunted: "Taunted!",
    WhatchaLookinAt: "Whatcha' lookin' at?",
    castEffectLine01: "- Inflicts target with the Taunted! Debuff.",
    castEffectLine02: "- Inflicts target with the Whatcha Lookin' At? Debuff.",
    synergies: ["Swiftness", "Once", "Taunt", "Debuff"],
  },
  {
    id: 95,
    character: "Phoenix",
    name: "Blazing Regeneration",
    image: blazingRegeneration,
    targetting: "All Allies",
    cost: "Cost: 2 Mana",
    stats02: " Burnt Debuff - Success Rate: 60% - Stacks Inflicted: (1/10).",
    Swiftness: "Swiftness",
    Burnt: "Burnt",
    castEffectLine01: "- Draw a skill and deal 5 damage to its owner.",
    castEffectLine02: "- This attack ignores healing gauge protection.",
    castEffectLine03:
      "- After the damage resolves, restore all allies' healing gauge to full.",
    castEffectLine04: "- Inflicts all targets with the Burnt Debuff.",
    synergies: [
      "Swiftness",
      "Once",
      "Restore Healing Gauge",
      "Pain Damage",
      "Debuff",
    ],
  },
  {
    id: 97,
    character: "Phoenix",
    name: "Legendary Beak",
    image: legendaryBeak,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 13 - Accuracy: 95% - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    Once: "Once",
    CannotBeFixed: "Cannot Be Fixed",
    IgnoreTaunt: "Ignore Taunt",
    castEffectLine01: "Shuffle 8 Peck skills into the Deck.",
    synergies: [
      "Swiftness",
      "Once",
      "Ignore Taunt",
      "Cannot Be Fixed",
      "Create Skill",
      "Attack",
    ],
  },
  {
    id: 99,
    character: "Phoenix",
    name: "Find Bread",
    image: findBread,
    targetting: "Self",
    cost: "Cost: 0 Mana",
    Swiftness: "Swiftness",
    castEffectLine01: "- 10% + (10% x Enemy Count)) chance to obtain bread.",
    castEffectLine02: "- This skill is excluded when you gain bread.",
    synergies: ["Swiftness", "Exclude", "Create Skill"],
  },
  {
    id: 100,
    character: "Phoenix",
    name: "Fetch",
    image: fetch,
    targetting: "Self",
    cost: "Cost: 50 Gold",
    Swiftness: "Swiftness",
    castEffectLine01:
      "- The last skill played from hand is placed at the top of the Deck",
    castEffectLine02: "- Excluded skills are not counted.",
    synergies: ["Swiftness", "Exclude", "Create Skill"],
  },
  {
    id: 101,
    character: "Phoenix",
    name: "Fly",
    image: fly,
    targetting: "Self",
    cost: "Cost: 0 Mana",
    Swiftness: "Swiftness",
    Once: "Once",
    castEffectLine01:
      "- View the skill at the top of the Deck and view the cost of two skills below it",
    synergies: ["Swiftness", "Once"],
  },
  {
    id: 102,
    character: "Phoenix",
    name: "Eternal Flame",
    image: eternalFlame,
    targetting: "Single Enemy",
    cost: "Cost: 1 Bread",
    stats01: " Damage: 21 - Accuracy: 96% - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    Once: "Once",
    castEffectLine01:
      "- Attack a random ally and enemy alternatively once you attack.",
    castEffectLine02:
      "- Dael 33% of this skill's damage when you attack an ally.",
    castEffectLine03: "- Repeat this until one is defeated.",
    castEffectLine04: "- Can only be used Once per stage.",
    synergies: ["Swiftness", "Once"],
  },
  {
    id: 103,
    character: "Phoenix",
    name: "Undying Sanctuary",
    image: undyingSanctuary,
    targetting: "Self",
    cost: "Cost: 1 Bread",
    Swiftness: "Swiftness",
    Once: "Once",
    UndyingSanctuary: "Undying Sanctuary",
    DeathsDoorImmunity: "Death's Door Immunity",
    castEffectLine01: "- Inflicts self with the Undying Sanctuary Buff.",
    synergies: ["Swiftness", "Once", "Death's Door Immunity", "Buff"],
  },
  {
    id: 104,
    character: "Phoenix",
    name: "Peck",
    image: peck,
    targetting: "Single Enemy",
    cost: "Cost: 2 Mana",
    stats01: " Damage: 14 - Accuracy: 96% - Critical Hit: 0%.",
    Overload: "Overload",
    Swiftness: "Once",
    IgnoreTaunt: "Ignore Taunt",
    castEffectLine01: "- Draw a skill from the Deck and cast it.",
    synergies: ["Overload", "Once", "Ignore Taunt", "Draw", "Attack"],
  },
  {
    id: 105,
    character: "Phoenix",
    name: "Throw Bread",
    image: throwBread,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana & 1 Bread",
    stats01: " Damage: 21 - Accuracy: 96% - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    castEffectLine01: "- Regain Throw Bread at the end of the battle.",
    synergies: ["Swiftness", "Once", "Create Skill", "Attack"],
  },

  // ------------ Pressel ----------- //

  {
    id: 106,
    character: "Pressel",
    name: "Healing Coil",
    image: healingCoil,
    targetting: "Single Ally",
    cost: "Cost: 1 Mana",
    stats01: "Healing: 16 - Critical Hit: 0%.",
    Overload: "Overload",
    Prophecy: "Prophecy",
    castEffectLine01:
      "- Prophecy Buff Attached: When used on a target other than the user, heal the user for 50% of healing amount.",
    synergies: ["Overload", "Additional Damage", "Prophecy", "Heal"],
  },
  {
    id: 107,
    character: "Pressel",
    name: "Holy Light",
    image: holyLight,
    targetting: "All Allies",
    cost: "Cost: 2 Mana",
    stats01: "Healing: 7 - Critical Hit: -10%.",
    Swiftness: "Swiftness",
    Prophecy: "Prophecy",
    EnhancedProphecy: "EnhancedProphecy",
    castEffectLine01: "- Inflicts self with the Enhanced Prophecy Buff (1/3).",
    synergies: [
      "Swiftness",
      "Enhanced Prophecy",
      "Prophecy",
      "Cost Down",
      "Heal",
    ],
  },
  {
    id: 108,
    character: "Pressel",
    name: "First Class To Heaven",
    image: firstClassToHeaven,
    targetting: "Single Enemy",
    cost: "Cost: 3 Mana",
    stats01: " Damage: 23 - Accuracy: 102% - Critical Hit: 0%.",
    Overload: "Overload",
    Critical: "Critical",
    IgnoreTaunt: "Ignore Taunt",
    Prophecy: "Prophecy",
    castEffectLine01:
      "- If this skill ddefeats an enemy, Overheal all allies by 1.",
    castEffectLine02: "- Prophecy Buff Attached: Deal 15 additional damage.",
    synergies: [
      "Overload",
      "Critical",
      "Ignore Taunt",
      "Prophecy",
      "Overheal",
      "Attack",
    ],
  },
  {
    id: 109,
    character: "Pressel",
    name: "Kill It!",
    image: killIt,
    targetting: "Single Enemy",
    cost: "Cost: 1 Mana",
    stats01: " Damage: 23 - Accuracy: 102% - Critical Hit: 0%.",
    stats02:
      " Armor Reduced! Debuff - Success Rate: 120% - Stacks Inflicted: (1/3).",
    stats02: " Taunt Debuff - Success Rate: 140% - Stacks Inflicted: N/A.",
    Swiftness: "Swiftness",
    IgnoreTaunt: "Ignore Taunt",
    Prophecy: "Prophecy",
    castEffectLine01:
      "- Inflicts target with the Armour Reduced! Debuff for 5 turns.",
    castEffectLine02: "- Inflicts target with the Taunt Debuff.",
    castEffectLine03:
      "- Prophecy Buff Attached: attack the target and an additional random enemy.",
    synergies: [
      "Swiftness",
      "Ignore Taunt",
      "Prophecy",
      "Armour Reduced!",
      "Armour Down",
      "Taunt",
      "Attack",
      "Debuff",
    ],
  },
  {
    id: 110,
    character: "Pressel",
    name: "Blinking Heal",
    image: blinkingHeal,
    targetting: "Single Ally",
    cost: "Cost: 1 Mana",
    stats01: " Healing: 14 - Critical Hit: 0%.",
    Swiftness: "Swiftness",
    Prophecy: "Prophecy",
    castEffectLine01: "- Choose one:",
    castEffectLine02: "- A) Increase the target's chance of being attacked.",
    castEffectLine03: "- B) Decrease the target's chance of being attacked",
    castEffectLine04: "- Prophecy Buff Attached: Increase healing amount by 2.",
    synergies: ["Swiftness", "Prophecy", "Heal", "Buff"],
  },
  {
    id: 111,
    character: "Pressel",
    name: "God's Blessing",
    image: godsBlessing,
    targetting: "Deck",
    cost: "Cost: 0 Mana",
    Overload: "Overload",
    CannotBeFixed: "Cannot Be Fixed",
    Prophecy: "Prophecy",
    castEffectLine01: "- Make a prophecy that prioritises attack skills.",
    castEffectLine02:
      "- Skills drawn by God's Blessing gain the Ignore Taunt & Tracking Buffs, alongside having both their Pain & Weakening Debuff Success Rates increased by 20%.",
    synergies: [
      "Overload",
      "Cannot Be Fixed",
      "Prophecy",
      "Add To Hand",
      "Ignore Taunt",
      "Tracking",
      "Debuff Up",
      "Buff",
    ],
  },
  {
    id: 112,
    character: "Pressel",
    name: "Purifying Barrier",
    image: purifyingBarrier,
    targetting: "Single Ally",
    cost: "Cost: 1 Mana",
    stats01: "Barrier: 12",
    Swiftness: "Swiftness",
    CannotBeFixed: "Cannot Be Fixed",
    Prophecy: "Prophecy",
    castEffectLine01: "- Remove a random debuff from the target.",
    castEffectLine02:
      "- Prophect Buff Attached: Remove on more debuff from the target.",
    synergies: ["Swiftness", "Prophecy", "Remove Debuff", "Barrier", "Buff"],
  },
  {
    id: 113,
    character: "Pressel",
    name: "Double Heal",
    image: doubleHeal,
    targetting: "Single Ally",
    cost: "Cost: 2 Mana",
    stats01: "Heal: 12 - Critical Hit: 0%",
    Overload: "Overload",
    Prophecy: "Prophecy",
    EnhancedProphecy: "EnhancedProphecy",
    ChainHeal: "Chain Heal",
    castEffectLine01:
      "- Chain Heal the selected target by 12 after 1 Countdown.",
    castEffectLine02: "- Inflict self with the Enhanced Prophecy Buff (1/3).",
    synergies: [
      "Overload",
      "Prophecy",
      "Enhanced Prophecy",
      "Chain Heal",
      "Heal",
      "Buff",
    ],
  },
  {
    id: 114,
    character: "Pressel",
    name: "Shining Pillar",
    image: shiningPillar,
    targetting: "Single Enemy",
    cost: "Cost: 3 Mana",
    stats01: "damage: 18 - Accuracy: 102% - Critical Hit: 25%",
    Swiftness: "Swiftness",
    Prophecy: "Prophecy",
    castEffectLine01:
      "- Heal all characters except yourself and the target for 5 (scales with Healing Power).",
    castEffectLine02: "- Prophecy Buff Attached: This skill costs 1 less Mana",
    synergies: ["Swiftness", "Prophecy", "Cost Down", "Heal", "Attack"],
  },
  {
    id: 115,
    character: "Pressel",
    name: "Adjust Aim",
    image: adjustAim,
    targetting: "Discard Pile",
    cost: "Cost: 1 Mana",
    Swiftness: "Swiftness",
    CannotBeFixed: "Cannot Be Fixed",
    Prophecy: "Prophecy",
    castEffectLine01:
      "- Shuffle all First Class To Heaven in the Discard Pile back into the Deck.",
    castEffectLine02:
      "- After the shuffle, make a Prophecy taht prioritises the user's skills.",
    castEffectLine03:
      "- Cost is reduced by 1 if the user is healed while this skill is in hand.",
    synergies: [
      "Swiftness",
      "Cannot Be Fixed",
      "Prophecy",
      "Add To Hand",
      "Add To Deck",
      "Cost Down",
      "Buff",
    ],
  },
  {
    id: 116,
    character: "Pressel",
    name: "Celestial Wing",
    image: celestialWing,
    targetting: "Self",
    cost: "Cost: 1 Mana",
    Swiftness: "Swiftness",
    Once: "Once",
    Prophecy: "Prophecy",
    celestialWing: "Celestial Wing",
    castEffectLine01:
      "- Move this Skill to the top of the Deck when the battle starts.",
    castEffectLine02: "- Inflicts self with the Celestial Wing Buff",
    synergies: ["Swiftness", "Once", "Prophecy", "Buff"],
  },
  {
    id: 117,
    character: "Pressel",
    name: "Guardian Angel",
    image: guardianAngel,
    targetting: "Single Ally",
    cost: "Cost: 1 Mana",
    stats01: "Heal: 18 - Critical Hit: 0%",
    Swiftness: "Swiftness",
    CannotBeFixed: "Cannot Be Fixed",
    celestialWing: "Celestial Wing",
    castEffectLine01: "- Overheal if target is at Death's Door.",
    synergies: ["Swiftness", "Cannot Be Fixed", "Overheal", "Heal"],
  },
];

export default skills;
